### ISSUE TITLE
Bug minting tokens on rinkeby

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/contractor#14]
**Describe the bug**
Typically on the first few are broadcast to network, then following ones aren't and time out waiting for receipt.

**Comment by mjkoo** [comment]
Oddly cannot reproduce locally deploying to rinkeby via infura, so unsure if its our node that's having issues (seeing a lot of ulimit errors on our node) or why contracts seems to complete successfully eventually (perhaps local tx signing isn't as reliable?) Next step would be to try an infura deploy from infrastructure i think.

**Comment by myhndl** [comment]
@mjkoo did you try an infura deploy?

**Comment by mjkoo** [comment]
Closed by #18
